/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef COOL_PRIVATE_H
#define COOL_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.0.378"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	378
#define COMPANY_NAME	""
#define FILE_VERSION	"0.0.0.378"
#define FILE_DESCRIPTION	"as COOL as an OOL"
#define INTERNAL_NAME	"COOL_MinGW"
#define LEGAL_COPYRIGHT	"GPL 3.0"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"COOL"
#define PRODUCT_VERSION	"0.0.0.378"

#endif /*COOL_PRIVATE_H*/
